export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_TASK = 'ADD_TASK';
export const CHANGE_STATUS_TASK = 'CHANGE_STATUS_TASK';
export const ADD_SUB_TASK = 'ADD_SUB_TASK';
export const MODAL_SHOW = 'MODAL_SHOW';
export const CHANGE_STATUS_SUB_TASK = 'CHANGE_STATUS_SUB_TASK';
export const ADD_DESCRIPTION_TO_TASK = 'ADD_DESCRIPTION_TO_TASK';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';