export const SET_PROJECTS_ARRAY_FROM_DB_TO_STORE = 'SET_PROJECTS_ARRAY_FROM_DB_TO_STORE';
export const SET_PROJECT_ID = 'SET_PROJECT_ID';
export const SET_TASKS_ARRAY_FROM_DB_TO_STORE = 'SET_TASKS_ARRAY_FROM_DB_TO_STORE';
export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_TASK = 'ADD_TASK';
export const CHANGE_STATUS_TASK = 'CHANGE_STATUS_TASK';
export const ADD_SUB_TASK = 'ADD_SUB_TASK';
export const MODAL_SHOW = 'MODAL_SHOW';
export const CHANGE_STATUS_SUB_TASK = 'CHANGE_STATUS_SUB_TASK';
export const ADD_DESCRIPTION_TO_TASK = 'ADD_DESCRIPTION_TO_TASK';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';

//===
export const GET_PROJECT = 'GET_PROJECT';
export const SET_PROJECT = 'SET_PROJECT';